#!/usr/bin/env bash
# Check which virtualization technology to use
# We prefer kvm, kqemu, userspace in that order.

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
ARCH="${ARCH-$(uname -m)}"
QEMU_CPU="${QEMU_CPU:-host}"

#ARGS=(-cpu cortex-a53)

BIN="/usr/bin/qemu-system-${ARCH}"

# Provide rng device sourcing the hosts /dev/urandom and other standard parameters
ARGS+=(-m "${MEMORY-1024}" -nographic -machine virt)

# only set -kernel if -initrd is specified
if [[ $* == *-initrd* ]]; then
    ARGS+=(-kernel "$VMLINUZ")
fi

echo "${0##*/}: $BIN ${ARGS[*]@Q} ${*@Q}"
exec "$BIN" "${ARGS[@]}" "$@"
