#!/bin/sh

command -v getargbool > /dev/null || . /lib/dracut-lib.sh
command -v get_luks_option > /dev/null || . /lib/dracut-crypt-lib.sh

generator_set_device_timeout() {
    local _name
    local _timeout="$2"

    _name=$(dev_unit_name "$1")

    if ! [ -f "$GENERATOR_DIR"/"${_name}".device.d/timeout.conf ]; then
        mkdir -p "$GENERATOR_DIR"/"${_name}".device.d
        {
            echo "# Automatically generated by ${0##*/}"
            echo
            echo "[Unit]"
            echo "JobTimeoutSec=$_timeout"
            echo "JobRunningTimeoutSec=$_timeout"
        } > "$GENERATOR_DIR"/"${_name}".device.d/timeout.conf
    fi
}

if ! getargbool 1 rd.luks; then
    # crypto LUKS detection is disabled
    return 0
fi

GENERATOR_DIR="$1"
[ -n "$GENERATOR_DIR" ] || return 1
[ -d "$GENERATOR_DIR" ] || mkdir -p "$GENERATOR_DIR"

_tries=$(get_luks_option tries)
_tries=${_tries:-0}

# For rd.luks.uuid= devices not in crypttab and without a key file, write a
# drop-in that overrides ExecStart with tries= from rd.luks.options= (default 0 = unlimited).
# systemd-cryptsetup-generator creates a device.wants/ symlink that auto-starts
# the service the moment the device appears, before any udev rule or initqueue
# hook can run. Generator drop-ins are merged after all generators finish but
# before any service starts, making this the only reliable place to set tries
# for this path
_cryptsetup_bin=$(command -v systemd-cryptsetup 2> /dev/null)
: "${_cryptsetup_bin:=/lib/systemd/systemd-cryptsetup}"

if [ -z "$(getarg rd.luks.key)" ]; then
    for _luksid in $(getargs rd.luks.uuid); do
        _luksid=${_luksid#keysource:}
        _luksid=${_luksid##luks-}
        # Already in crypttab, tries= is set there
        grep -q "$_luksid" /etc/crypttab 2> /dev/null && continue
        # Hyphens are escaped to \x2d in systemd unit instance names
        _escaped=$(dev_unit_name "luks-${_luksid}")
        _dropin="${GENERATOR_DIR}/systemd-cryptsetup@${_escaped}.service.d"
        mkdir -p "$_dropin"
        {
            echo "# Automatically generated by ${0##*/}"
            echo "[Service]"
            echo "ExecStart="
            printf 'ExecStart=%s attach luks-%s /dev/disk/by-uuid/%s - tries=%s\n' \
                "$_cryptsetup_bin" "$_luksid" "$_luksid" "$_tries"
        } > "$_dropin/tries.conf"
    done
fi

[ -e /etc/crypttab ] || return 0

timeout=$(getarg rd.timeout)
timeout=${timeout:-infinity}
while read -r _ _source_device _ || [ -n "$_source_device" ]; do
    _dev=$(label_uuid_to_dev "$_source_device")
    generator_set_device_timeout "$_dev" "$timeout"
done < /etc/crypttab
