# This file is part of dracut chrony module.
# SPDX-License-Identifier: GPL-2.0-or-later

# Record the rate at which the system clock gains/losses time.
driftfile /run/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync

# Save NTS keys and cookies.
ntsdumpdir /run/chrony

# Specify directory for log files.
logdir /run/chrony/log

# First, use NTP sources parsed by dracut from the kernel command line.
sourcedir /run/chrony/dracut.sources.d

# Second, use NTP sources from DHCP.
sourcedir /run/chrony-dhcp
