ARG DISTRIBUTION=alpine
FROM docker.io/${DISTRIBUTION}

# prefer running tests with clang
ENV CC=clang

# ovmf is not installed as systemd-boot-efistub is not available
# see https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61369

# dash is not installed to run test suite only with busybox and bash
# (without requiring dash)

# ntfs-3g and erofs-utils not installed as the corresponding kernel
# modules are not enabled with linux-virt

# multipath-tools is not installed as it does not work well

# cargo is not installed only in this container to test packaging without cargo

RUN apk add --no-cache \
    asciidoc \
    asciidoctor \
    bash \
    binutils \
    blkid \
    bluez \
    btrfs-progs \
    busybox \
    bzip2 \
    clang \
    coreutils \
    cpio \
    cryptsetup \
    curl \
    device-mapper \
    dhclient \
    dmraid \
    dosfstools \
    dracut \
    e2fsprogs \
    elogind \
    eudev \
    file \
    findmnt \
    f2fs-tools \
    git \
    gpg \
    grep \
    iputils \
    jfsutils \
    jq \
    kbd \
    keyutils \
    kmod \
    kmod-dev \
    libcap-utils \
    linux-virt \
    losetup \
    lvm2 \
    make \
    mdadm \
    mtools \
    musl-fts-dev \
    nbd \
    nvme-cli \
    open-iscsi \
    openssh \
    parted \
    partx \
    pigz \
    plymouth-themes \
    procps \
    qemu-img \
    qemu-system-x86_64 \
    rng-tools \
    sed \
    sfdisk \
    squashfs-tools \
    swtpm \
    util-linux-misc \
    xfsprogs \
    xz

# workaround for --enable-split-usr
# see https://github.com/eudev-project/eudev/pull/246
# needed to run RAID tests
RUN \
  mkdir -p /lib/udev/rules.d && cp /usr/lib/udev/rules.d/* /lib/udev/rules.d/
