# Test coverage provided by this container:
# - network-legacy
# - mkosi-initrd
# - hmaccalc (fido)
# - rdma out of tree dracut module

FROM registry.opensuse.org/opensuse/tumbleweed:latest

# prefer running tests with btrfs
ENV TEST_FSTYPE=btrfs

# Install needed packages for the dracut CI container
RUN zypper --non-interactive install --no-recommends \
    asciidoc \
    bash-completion \
    btrfsprogs \
    cargo \
    cryptsetup \
    dbus-broker \
    dhcp-client \
    dhcp-server \
    distribution-gpg-keys \
    dmraid \
    e2fsprogs \
    erofs-utils \
    gcc \
    git \
    hmaccalc \
    iproute \
    iputils \
    iscsiuio \
    kbd \
    kernel \
    libkmod-devel \
    lvm2 \
    make \
    mdadm \
    mkosi-initrd \
    nbd \
    NetworkManager \
    nfs-utils \
    open-iscsi \
    parted \
    pciutils \
    procps \
    python3-pefile \
    qemu-kvm \
    squashfs \
    swtpm \
    systemd-boot \
    systemd-experimental \
    tgt \
    tpm2.0-tools \
    /usr/bin/qemu-system-$(uname -m) \
    util-linux-systemd \
    && zypper --non-interactive dist-upgrade --no-recommends && zypper --non-interactive clean

# force non-hostonly mode, but keep all the other config
RUN \
  echo 'hostonly="no"' > /usr/lib/dracut/dracut.conf.d/02-dist.conf
