# Test coverage provided by this container:
# - arm64
# - dash default shell (instead of bash)
# - runit (instead of systemd)
# - eudev (instead of systemd-udev)
# - elogind (instead of logind)
# - UEFI boot, UKI (without systemd)
# - zfs and zfs out of tree dracut module
# - gzip compression
# - clang
# - dbus-daemon
# - network: network-legacy, network-manager

# Not installed
# - kernel-install is not available

FROM ghcr.io/void-linux/void-glibc-full

# prefer running tests with zfs and clang
ENV TEST_FSTYPE=zfs
ENV CC=clang

RUN xbps-install -Syu xbps && xbps-install -yu \
    asciidoc \
    bash \
    binutils \
    btrfs-progs \
    cargo \
    clang \
    cpio \
    cryptsetup \
    dhclient \
    dhcp \
    e2fsprogs \
    edk2-ovmf \
    elfutils \
    elogind \
    erofs-utils \
    eudev \
    glibc \
    gnupg \
    iproute2 \
    iputils \
    jq \
    kbd \
    libkmod-devel \
    linux \
    lvm2 \
    make \
    mdadm \
    NetworkManager \
    nfs-utils \
    nvme-cli \
    parted \
    pkg-config \
    plymouth \
    qemu \
    squashfs-tools \
    systemd-boot-efistub \
    ncurses-base \
    ukify \
    xorriso \
    zfs \
    && rm -rf /var/cache/xbps \
    && rm -rf /usr/lib/firmware
