ARG DISTRIBUTION=fedora
ARG REGISTRY=registry.fedoraproject.org

FROM ${REGISTRY}/${DISTRIBUTION}

# export ARG
ARG DISTRIBUTION

RUN \
    dnf config-manager --set-enabled crb; \
    dnf -y install --setopt=install_weak_deps=False \
    erofs-utils
