FROM registry.opensuse.org/opensuse/tumbleweed-dnf:latest

# Install needed packages for the dracut CI container
RUN dnf -y install --setopt=install_weak_deps=False \
    asciidoc \
    bash-completion \
    btrfsprogs \
    bzip2 \
    cargo \
    cryptsetup \
    dash \
    dbus-broker \
    dhcp-client \
    dhcp-server \
    dmraid \
    e2fsprogs \
    erofs-utils \
    gcc \
    git \
    hmaccalc \
    iproute \
    iputils \
    iscsiuio \
    kbd \
    kernel \
    libkmod-devel \
    lvm2 \
    make \
    mdadm \
    nbd \
    NetworkManager \
    nfs-utils \
    open-iscsi \
    parted \
    pigz \
    procps \
    qemu-kvm \
    rng-tools \
    rpm-build \
    sbsigntools \
    ShellCheck \
    shfmt \
    squashfs \
    strace \
    systemd-boot \
    systemd-experimental \
    tar \
    tcpdump \
    tgt \
    tpm2.0-tools \
    /usr/bin/qemu-system-$(uname -m) \
    util-linux-systemd \
    wget \
    xz \
    && dnf -y update && dnf clean all

# configuration in the package is not compatible
# with the upstream CI, lets remove it
RUN \
  rm -rf /usr/lib/dracut/dracut.conf.d
