# Test coverage provided by this container:
# - network-legacy
# - mkosi-initrd
# - hmaccalc (fido)
# - rdma out of tree dracut module

FROM registry.opensuse.org/opensuse/tumbleweed:latest

# Install needed packages for the dracut CI container
RUN zypper --non-interactive install --no-recommends \
    asciidoc \
    bash-completion \
    btrfsprogs \
    cargo \
    cryptsetup \
    dbus-broker \
    dhcp-client \
    dhcp-server \
    distribution-gpg-keys \
    dmraid \
    e2fsprogs \
    erofs-utils \
    gcc \
    git \
    hmaccalc \
    iproute \
    iputils \
    iscsiuio \
    kbd \
    kernel \
    libkmod-devel \
    lvm2 \
    make \
    mdadm \
    nbd \
    NetworkManager \
    nfs-utils \
    open-iscsi \
    parted \
    pciutils \
    procps \
    python3-pefile \
    qemu-kvm \
    squashfs \
    swtpm \
    systemd-boot \
    systemd-experimental \
    tgt \
    tpm2.0-tools \
    /usr/bin/qemu-system-$(uname -m) \
    util-linux-systemd \
    && zypper --non-interactive dist-upgrade --no-recommends

# install mkosi from source
RUN \
  cd / \
  && git clone https://github.com/systemd/mkosi \
  && ln -s /mkosi/bin/mkosi /usr/bin/mkosi \
  && ln -s /mkosi/bin/mkosi-initrd /usr/bin/mkosi-initrd \
  && zypper --non-interactive remove busybox-diffutils busybox-less \
  && /usr/bin/mkosi dependencies | xargs zypper --non-interactive install
