FROM docker.io/debian:latest

# dmraid is no longer installed
# see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056944

# Install needed packages for the dracut CI container
# Install dracut as a linux-initramfs-tool provider so that the default initramfs-tool package does not get installed
RUN apt-get update -y -qq && apt-get upgrade -y -qq && apt-get install -y -qq --no-install-recommends dracut && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    asciidoc \
    astyle \
    bluez \
    btrfs-progs \
    busybox-static \
    bzip2 \
    ca-certificates \
    cargo \
    cifs-utils \
    console-setup \
    cpio \
    cryptsetup \
    curl \
    docbook \
    docbook-xml \
    docbook-xsl \
    erofs-utils \
    fcoe-utils \
    fdisk \
    file \
    g++ \
    gawk \
    git \
    gpg \
    iputils-arping \
    iputils-ping \
    isc-dhcp-client \
    isc-dhcp-server \
    iscsiuio \
    jq \
    kmod \
    less \
    libkmod-dev \
    linux-image-generic \
    lvm2 \
    make \
    mdadm \
    multipath-tools \
    nbd-client \
    nbd-server \
    network-manager \
    nfs-kernel-server \
    ntfs-3g \
    nvme-cli \
    open-iscsi \
    openssh-client \
    ovmf \
    parted \
    pcscd \
    pigz \
    plymouth \
    pkg-config \
    procps \
    qemu-kvm \
    rng-tools5 \
    sbsigntool \
    shellcheck \
    squashfs-tools \
    strace \
    systemd-boot-efi \
    systemd-container \
    systemd-coredump \
    systemd-resolved \
    systemd-timesyncd \
    tcpdump \
    tgt \
    thin-provisioning-tools \
    tpm2-tools \
    vim \
    wget \
    zstd \
    && apt-get clean
