# Test coverage provided by this container:
# - xfs, ntfs-3g
# - mkinitcpio, mkosi
# - sbsigntools
# - qrencode (systemd-bsod)
# - rdma out of tree dracut module

# Not installed
# - busybox (no need, tested elsewhere)
# - cifs-utils (no need, tested elsewhere)
# - openssh (no need, tested elsewhere)
# - rng-tools (does not start, https://github.com/dracut-ng/dracut-ng/pull/290#issuecomment-2138184351)

FROM docker.io/archlinux

# prefer running tests with xfs
ENV TEST_FSTYPE=xfs

RUN pacman --noconfirm -Syu \
    asciidoc \
    bluez \
    btrfs-progs \
    busybox \
    cargo \
    cpio \
    dhclient \
    dhcp \
    dmraid \
    elfutils \
    erofs-utils \
    gcc \
    jq \
    linux \
    lvm2 \
    make \
    mdadm \
    mkosi \
    multipath-tools \
    nbd \
    networkmanager \
    nfsidmap \
    nfs-utils \
    ntfs-3g \
    nvme-cli \
    open-iscsi \
    parted \
    pciutils \
    pkgconf \
    plymouth \
    qemu \
    qrencode \
    sbsigntools \
    squashfs-tools \
    swtpm \
    systemd-ukify \
    tgt \
    tpm2-tools \
    xfsprogs \
    && yes | pacman -Scc
