FROM docker.io/archlinux

# prefer running tests with xfs
ENV TEST_FSTYPE=xfs

RUN pacman --noconfirm -Syu \
    asciidoc \
    base-devel \
    bluez \
    btrfs-progs \
    busybox \
    cargo \
    cifs-utils \
    connman \
    cpio \
    dhclient \
    dhcp \
    dmraid \
    elfutils \
    erofs-utils \
    f2fs-tools \
    git \
    glibc \
    jfsutils \
    jq \
    linux \
    lvm2 \
    lzop \
    mdadm \
    mkosi \
    multipath-tools \
    nbd \
    networkmanager \
    nfsidmap \
    nfs-utils \
    ntfs-3g \
    nvme-cli \
    open-iscsi \
    openssh \
    parted \
    pigz \
    plymouth \
    qemu \
    qrencode \
    rng-tools \
    sbsigntools \
    squashfs-tools \
    swtpm \
    systemd-ukify \
    tgt \
    tpm2-tools \
    xfsprogs \
    && yes | pacman -Scc
