FROM registry.fedoraproject.org/fedora:latest

# Install needed packages for the dracut CI container
RUN dnf -y install --setopt=install_weak_deps=False \
    asciidoc \
    astyle \
    bash-completion \
    bluez \
    btrfs-progs \
    busybox \
    bzip2 \
    cargo \
    cifs-utils \
    cryptsetup \
    dash \
    dbus-daemon \
    device-mapper-multipath \
    dhcp-client \
    dhcp-server \
    dmraid \
    e2fsprogs \
    erofs-utils \
    f2fs-tools \
    fcoe-utils \
    fuse3 \
    gcc \
    git \
    iproute \
    iputils \
    iscsi-initiator-utils \
    jfsutils \
    jq \
    kbd \
    kernel \
    kmod-devel \
    libkcapi-hmaccalc \
    libselinux-utils \
    lvm2 \
    lzop \
    make \
    mdadm \
    memstrack \
    mkosi \
    mksh \
    nbd \
    ndctl \
    NetworkManager \
    nfs-utils \
    ntfs-3g \
    ntfsprogs \
    nvme-cli \
    parted \
    pcsc-lite \
    pigz \
    plymouth \
    qemu \
    qrencode \
    rng-tools \
    rpm-build \
    sbsigntools \
    scsi-target-utils \
    ShellCheck \
    shfmt \
    squashfs-tools \
    strace \
    systemd-boot-unsigned \
    systemd-networkd \
    systemd-resolved \
    systemd-ukify \
    tar \
    tcpdump \
    tpm2-tools \
    wget \
    xfsprogs \
    xz \
    && dnf -y update && dnf clean all

# discard configurations that enforce an out-of-tree dracut module
# which would break test automation
# since this is a distro specific change, lets do it in the container
RUN \
  rm -rf /usr/lib/dracut/dracut.conf.d/50-nss-softokn.conf
