ARG DISTRIBUTION=ubuntu
FROM docker.io/${DISTRIBUTION}

# export ARG
ARG DISTRIBUTION

# prefer running tests in verbose mode
ENV V=2

# Install needed packages for the dracut CI container
# The Linux kernel is only readable by root. See https://launchpad.net/bugs/759725
RUN apt-get update -y -qq && apt-get upgrade -y -qq

# extra packages for rolling
RUN if [ "${DISTRIBUTION}" = "ubuntu:rolling" ] ; then \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    systemd-cryptsetup \
    systemd-repart \
    ; fi

RUN \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    asciidoc \
    bluez \
    btrfs-progs \
    busybox-static \
    bzip2 \
    ca-certificates \
    cargo \
    cifs-utils \
    console-setup \
    cpio \
    cryptsetup \
    curl \
    docbook \
    docbook-xml \
    docbook-xsl \
    erofs-utils \
    f2fs-tools \
    fcoe-utils \
    fdisk \
    file \
    g++ \
    git \
    gpg \
    iputils-arping \
    iputils-ping \
    isc-dhcp-client \
    isc-dhcp-server \
    iscsiuio \
    jfsutils \
    jq \
    kmod \
    libkmod-dev \
    linux-image-generic \
    lvm2 \
    make \
    mdadm \
    multipath-tools \
    nbd-client \
    nbd-server \
    network-manager \
    nfs-kernel-server \
    ntfs-3g \
    nvme-cli \
    open-iscsi \
    openssh-client \
    ovmf \
    parted \
    pcscd \
    pigz \
    pkg-config \
    plymouth-themes \
    procps \
    qemu-kvm \
    rng-tools5 \
    sbsigntool \
    squashfs-tools \
    swtpm \
    systemd-boot-efi \
    systemd-container \
    systemd-coredump \
    systemd-resolved \
    systemd-timesyncd \
    systemd-ukify \
    tgt \
    thin-provisioning-tools \
    tpm2-tools \
    xfsprogs \
    zstd \
    && apt-get clean \
    && chmod a+r /boot/vmlinu*
