FROM docker.io/archlinux

RUN pacman --noconfirm -Syu \
    asciidoc \
    astyle \
    base-devel \
    btrfs-progs \
    connman \
    cpio \
    dash \
    dhclient \
    dhcp \
    dmraid \
    git \
    glibc \
    linux \
    lvm2 \
    mdadm \
    multipath-tools \
    nbd \
    networkmanager \
    nfsidmap \
    nfs-utils \
    ntfs-3g \
    open-iscsi \
    parted \
    pigz \
    qemu \
    shellcheck \
    shfmt \
    squashfs-tools \
    strace \
    tcpdump \
    tgt \
    vi \
    && yes | pacman -Scc
