# Test coverage provided by this container:
# - 3cpio
# - arm64
# - dash default shell (instead of bash)
# - curl (url-lib)
# - mawk (instead of gawk)
# - zstd compression
# - verbose logging for tests
# - dbus-daemon
# - network: network-manager, systemd-networkd

ARG DISTRIBUTION=debian
FROM docker.io/${DISTRIBUTION}

# export ARG
ARG DISTRIBUTION

# Install dracut as a linux-initramfs-tool provider so that the default initramfs-tool package does not get installed
RUN apt-get update -y -qq && apt-get upgrade -y -qq && apt-get install -y -qq --install-recommends dracut dracut-network dracut-test

# Install 3cpio where available
RUN if [ "$DISTRIBUTION" != "debian:latest" ] ; then cpio=3cpio; else cpio=cpio; fi; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    $cpio

# use GNU coreutils instead of uutil's coreutils until https://github.com/uutils/coreutils/issues/9057 and https://launchpad.net/bugs/2129037 are fixed
RUN if [ "$DISTRIBUTION" = "ubuntu:rolling" ]; then \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    coreutils-from-gnu coreutils-from-uutils- --allow-remove-essential; \
    fi

# libarchive is required by systemd-import for systemd >= v259: https://launchpad.net/bugs/2139822
RUN \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    asciidoctor \
    bluez \
    btrfs-progs \
    ca-certificates \
    cargo \
    console-data \
    cryptsetup \
    curl \
    dmsetup \
    dnsmasq \
    docbook \
    docbook-xml \
    docbook-xsl \
    erofs-utils \
    fdisk \
    file \
    gcc \
    gpg \
    gpg-agent \
    iputils-arping \
    iputils-ping \
    iproute2 \
    isc-dhcp-server \
    iscsiuio \
    jq \
    kbd \
    kmod \
    libarchive13t64 \
    libfido2-1 \
    libkmod-dev \
    libsystemd-dev \
    linux-image-generic \
    lvm2 \
    make \
    mdadm \
    multipath-tools \
    nbd-client \
    nbd-server \
    network-manager \
    nfs-kernel-server \
    ntfs-3g \
    nvme-cli \
    open-iscsi \
    ovmf \
    parted \
    pcscd \
    pkg-config \
    plymouth-themes \
    procps \
    python3 \
    qemu-efi-aarch64 \
    qemu-kvm \
    qemu-system \
    rng-tools5 \
    squashfs-tools \
    swtpm \
    systemd-boot-efi \
    systemd-container \
    systemd-coredump \
    systemd-cryptsetup \
    systemd-repart \
    systemd-resolved \
    systemd-sysv \
    systemd-timesyncd \
    systemd-ukify \
    tgt \
    thin-provisioning-tools \
    tpm2-tools \
    util-linux-extra \
    xfsprogs \
    xorriso \
    zstd \
    && apt-get clean
