# Test coverage provided by this container:
# - arm64
# - hostonly
# - memstrack
# - ndctl (for nvdimm)
# - fcoe-utils (Fibre Channel over Ethernet)
# - curl (url-lib)
# - cifs-utils (cifs)
# - openssh (ssh-client)
# - rsyslog (syslog)
# - libkcapi-hmaccalc (fido)

ARG DISTRIBUTION=fedora
ARG REGISTRY=registry.fedoraproject.org

FROM ${REGISTRY}/${DISTRIBUTION}

# export ARG
ARG DISTRIBUTION

RUN \
if [[ "${DISTRIBUTION}" =~ "centos:" ]]; then \
    dnf config-manager --set-enabled crb; \
else \
    dnf -y install --setopt=install_weak_deps=False \
    btrfs-progs \
    busybox \
    dhcp-client \
    dhcp-server \
    dmraid \
    nbd \
    /usr/bin/qemu-system-$(uname -m) \
    scsi-target-utils \
    systemd-networkd \
; fi

RUN dnf -y install --setopt=install_weak_deps=False \
    asciidoc \
    bash-completion \
    bluez \
    cargo \
    cifs-utils \
    cryptsetup \
    dbus-daemon \
    device-mapper-multipath \
    e2fsprogs \
    erofs-utils \
    fcoe-utils \
    fuse3 \
    gcc \
    iproute \
    iputils \
    iscsi-initiator-utils \
    jq \
    kbd \
    kernel \
    kmod-devel \
    libkcapi-hmaccalc \
    libselinux-utils \
    lvm2 \
    make \
    mdadm \
    memstrack \
    ndctl \
    NetworkManager \
    nfs-utils \
    nvme-cli \
    parted \
    pcsc-lite \
    plymouth \
    qemu-kvm \
    rng-tools \
    rsyslog \
    squashfs-tools \
    swtpm \
    systemd-boot-unsigned \
    systemd-resolved \
    systemd-ukify \
    tpm2-tools \
    && dnf -y update && dnf clean all

# discard configurations that enforce an out-of-tree dracut module breaking CI
# CentOS Stream ships only qemu-kvm, but it disables the KVM accel when it's not available
RUN \
    rm -rf /usr/lib/dracut/dracut.conf.d/50-nss-softokn.conf && \
    [[ -e /usr/bin/qemu-kvm ]] || ln -sf /usr/libexec/qemu-kvm /usr/bin/qemu-kvm && \
    [[ -e /usr/bin/qemu-system-$(uname -m) ]] || ln -sv /usr/libexec/qemu-kvm /usr/bin/qemu-system-$(uname -m)
