# Test coverage provided by this container:
# - arm64
# - dash default shell (instead of bash)
# - mawk (instead of gawk)
# - pigz compression
# - verbose logging for tests

# Not installed
# - dmraid (no longer maintained, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056944)
# - plymouth-themes (not yet working with dracut, https://bugs.launchpad.net/ubuntu/+source/dracut/+bug/1596220)
# - iscsiuio, open-iscsi (not yet working with dracut, https://bugs.launchpad.net/ubuntu/+source/open-iscsi/+bug/2072484)
# - busybox-static

ARG DISTRIBUTION=ubuntu
FROM docker.io/${DISTRIBUTION}

# export ARG
ARG DISTRIBUTION

# prefer running tests in verbose mode
ENV V=2

# Install dracut as a linux-initramfs-tool provider so that the default initramfs-tool package does not get installed
RUN apt-get update -y -qq && apt-get upgrade -y -qq && apt-get install -y -qq --no-install-recommends dracut

# extra packages for rolling
RUN if [ "${DISTRIBUTION}" = "ubuntu:rolling" ] ; then \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    systemd-cryptsetup \
    systemd-repart \
    ; fi

RUN \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    asciidoc \
    bluez \
    btrfs-progs \
    ca-certificates \
    cargo \
    console-setup \
    cpio \
    cryptsetup \
    docbook \
    docbook-xml \
    docbook-xsl \
    erofs-utils \
    fdisk \
    file \
    gcc \
    gpg \
    iputils-arping \
    iputils-ping \
    isc-dhcp-client \
    isc-dhcp-server \
    jq \
    kmod \
    libkmod-dev \
    linux-image-generic \
    lvm2 \
    make \
    mdadm \
    multipath-tools \
    nbd-client \
    nbd-server \
    network-manager \
    nfs-kernel-server \
    ntfs-3g \
    nvme-cli \
    ovmf \
    parted \
    pcscd \
    pigz \
    pkg-config \
    procps \
    qemu-kvm \
    rng-tools5 \
    squashfs-tools \
    swtpm \
    systemd-boot-efi \
    systemd-container \
    systemd-coredump \
    systemd-resolved \
    systemd-sysv \
    systemd-timesyncd \
    systemd-ukify \
    tgt \
    thin-provisioning-tools \
    tpm2-tools \
    && apt-get clean \
    && chmod a+r /boot/vmlinu*
