# Tiny container with busybox
# GNU coreutils and GNU grep should not be installed

FROM docker.io/alpine:edge

RUN apk add --no-cache \
    bash \
    e2fsprogs \
    eudev \
    findmnt \
    gcc \
    kmod-dev \
    linux-virt \
    make \
    musl-dev  \
    musl-fts-dev \
    qemu-system-$(uname -m)
