# Test coverage provided by this container:
# - dash default shell (instead of bash)
# - runit (instead of systemd)
# - eudev (instead of systemd-udev)
# - elogind (instead of logind)
# - uki (without systemd)
# - zfs and zfs out of tree dracut module
# - gzip compression
# - clang

FROM ghcr.io/void-linux/void-glibc-full

# prefer running tests with zfs and clang
ENV TEST_FSTYPE=zfs
ENV CC=clang

RUN xbps-install -Syu xbps && xbps-install -yu \
    asciidoc \
    bash \
    binutils \
    btrfs-progs \
    cargo \
    clang \
    cpio \
    cryptsetup \
    dhclient \
    dhcp \
    dmraid \
    e2fsprogs \
    edk2-ovmf \
    elfutils \
    elogind \
    erofs-utils \
    eudev \
    glibc \
    gnupg \
    iproute2 \
    iputils \
    jq \
    kbd \
    libkmod-devel \
    linux \
    lvm2 \
    make \
    mdadm \
    nfs-utils \
    nvme-cli \
    parted \
    pkg-config \
    plymouth \
    qemu-system-amd64 \
    squashfs-tools \
    systemd-boot-efistub \
    ncurses-base \
    ukify \
    zfs \
    && rm -rf /var/cache/xbps
