# Tiny container with busybox
# GNU coreutils and GNU grep should not be installed

FROM docker.io/alpine:edge

RUN apk add --no-cache \
    bash \
    e2fsprogs \
    eudev \
    findmnt \
    gcc \
    kmod-dev \
    linux-virt \
    make \
    musl-dev  \
    musl-fts-dev \
    qemu-system-$(uname -m)

# workaround for https://gitlab.alpinelinux.org/alpine/aports/-/issues/17907
RUN \
  ln -sf /boot/vmlinuz-virt /boot/vmlinuz-$(cd /lib/modules; ls -1 | tail -1)
