---
name: Manual test

on:  # yamllint disable-line rule:truthy
    workflow_dispatch:
        inputs:
            test:
                description: "Array of tests to run, such as [11,12]"
                default: "[]"
            container:
                type: choice
                description: 'distro'
                default: 'all'
                options:
                    - "all"
                    - "alpine"
                    - "alpine:edge"
                    - "centos:stream10-development"
                    - "fedora"
                    - "fedora:rawhide"
                    - "arch"
                    - "debian"
                    - "debian:sid"
                    - "ubuntu"
                    - "ubuntu:devel"
                    - "ubuntu:rolling"
                    - "opensuse"
                    - "gentoo"
                    - "void"
            env:
                description: 'Environment (optional)'
                default: '{"DEBUGFAIL": "rd.debug"}'
            registry:
                description: 'Registry for containers, such as ghcr.io/dracut-ng'

env:
    ${{ fromJSON(inputs.env) }}

jobs:
    matrix:
        runs-on: ubuntu-24.04
        outputs:
            registry: ${{ steps.set-matrix.outputs.registry }}
            container: ${{ steps.set-matrix.outputs.container }}
            tests: ${{ steps.set-matrix.outputs.tests }}
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - id: set-matrix
              name: "Set Matrix"
              run: |
                   [[ "${{ inputs.registry }}" != '' ]] && echo "registry=\"${{ inputs.registry }}\"" >> $GITHUB_OUTPUT \
                   || ( echo "registry=\"ghcr.io/${{ github.repository_owner }}\"" >> $GITHUB_OUTPUT )
                   [[ "${{ inputs.container }}" != 'all' ]] && echo "container=[\"${{ inputs.container }}\"]" >> $GITHUB_OUTPUT \
                   || ( containers=$(find test/container -name "Dockerfile-*" | cut -d\- -f2 | tr '[:upper:]' '[:lower:]' | sed -z 's/\n/","/g'); echo "container=[\"${containers%??}]" >> $GITHUB_OUTPUT )
                   [[ "${{ toJson(fromJson(inputs.test)) }}" != '[]' ]] && echo "tests=${{ inputs.test }}" >> $GITHUB_OUTPUT \
                   || ( tests=$(find test -type d -a -name "TEST-*" | cut -d\- -f2 | sed -z 's/\n/","/g' ); echo "tests=[\"${tests%??}]" >> $GITHUB_OUTPUT )
    test:
        needs: matrix
        runs-on: ubuntu-24.04
        timeout-minutes: 20
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: ${{ fromJSON(needs.matrix.outputs.container) }}
                test: ${{ fromJSON(needs.matrix.outputs.tests) }}
            fail-fast: false
        container:
            image: ${{ fromJSON(needs.matrix.outputs.registry) }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: "${{ matrix.container }} ${{ matrix.test }}"
              run: ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
